apiVersion: v1
kind: PersistentVolume
metadata:
  name: meri-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
      path: "/mnt"
  storageClassName: local-storage    
